### ISSUE TITLE
Typo in What is Hive image

### ISSUE THREAD

**Issue by svpernova09** [christianfuerst/hiveonboard#15]
There's a typo `Socail Networking`on the URL: https://hiveonboard.com/what-is-hive The file `https://hiveonboard.com/images/more_than_cryptocurrency_banner.png` -> https://github.com/christianfuerst/hiveonboard/blob/master/public/images/more_than_cryptocurrency_banner.png

I didn't see source assets for this image so I wanted to let you know about the typo.

<img width="1304" alt="Screen Shot 2020-06-14 at 18 16 07" src="https://user-images.githubusercontent.com/967362/84606416-a0290d00-ae6b-11ea-9194-a5a3e7564184.png">

**Comment by christianfuerst** [comment]
Thanks for reporting! Will reach out to the creator of this image.
