### ISSUE TITLE
Error on create-account page

### ISSUE THREAD

**Issue by eapo** [christianfuerst/hiveonboard#36]
The following errors are on the https://hiveonboard.com/create-account page after submitting SMS code:
![image](https://user-images.githubusercontent.com/4000929/123344902-841b7980-d55d-11eb-914f-e7f265d19603.png)

**Comment by christianfuerst** [comment]
Hey, just checked backend log files around the time you posted this issue.
I recognized a few timeouts from HIVE nodes while trying to create an account on our backend.

It should be resolved by now - would be great to hear, if you can confirm.

Thanks and best wishes,
roomservice
