### ISSUE TITLE
Signup with VIP link not showing up in the main referred accounts list

### ISSUE THREAD

**Issue by brianoflondon** [christianfuerst/hiveonboard#39]
Maybe this will show up later but the account `@podnews` signed up with a VIP link from my `@brianoflondon` account. I can see the signup on the VIP page but its not showing in the main page.

**Comment by christianfuerst** [comment]
Hi @brianoflondon thanks for reaching out.
A few days ago a parsing backend service was on stuck, which could lead to this issue.

Could you check if the account shows up now? Should hopefully be fixed now.

**Comment by brianoflondon** [comment]
Yes the notification showed up 24 hours later.
