### ISSUE TITLE
UI erroneously reports success, ticket consumed after creator-api failure

### ISSUE THREAD

**Issue by lemony-cricket** [christianfuerst/hiveonboard#51]
UI reports account creation success even if the remote creator-api instance reports failure. This also results in consumption of the ticket. Basically, hiveonboard treats an account creation failure as a success and everything proceeds accordingly. Users do not notice anything wrong until they try to use the account which does not exist.

After investigation I believe this error was caused by a logic error here: https://github.com/christianfuerst/hiveonboard/blob/8b966f0b80587793efbe454001f950d774eccbad/functions/index.js#L220

A PR is forthcoming.

**Comment by christianfuerst** [comment]
Thanks for pointing this out! Seems like the function never stepped into this if statement before, like it was intended.
Merging the pr as writing this.
