### ISSUE TITLE
Client-side key generation

### ISSUE THREAD

**Issue by skzap** [christianfuerst/hiveonboard#8]
You should already know why a private key should be generated by the users themselves on the client-side. **Transmitting a private key through the wire is risky** (even with SSL). When it could be generated client-side easily with hive-js, it's being stupid.

**Comment by skzap** [comment]
Oh and obviously, only the public keys should be sent to the server after being generated. The user should be offered a downloadable file (pdf or txt), as well as a qrcode if he wants to store his key as a picture.

**Comment by christianfuerst** [comment]
Yes, this was stupid, it's fixed in https://github.com/christianfuerst/hiveonboard/commit/2ae67bdb7e6bf89b77f3f6d49e6ea8c76de3a92c
